config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'artworks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :artworks, only: [:index, :show, :new, :create, :edit, :destroy] do
    collection do
      resources :my_artworks, only: :index
    end
  resources :bookings, only: [:create]
  end
  resource :dashboard, only: :show
  resources :bookings, only: [:update, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_many_attached :photos
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :rate, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: %w[painting drawing sculpture graphic\ design ceramic photography] }

  include PgSearch::Model
  pg_search_scope :global_search,
      against: [:name, :category, :description, :address],
      associated_against: {
        user: [:username]
      },
      using: {
        tsearch: { prefix: true }
      }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :artwork
  has_many :reviews, dependent: :destroy
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_cannot_come_before_start_date # ,:booking_dates_cannot_be_in_the_past
  # validates :total_price, presence: true
  # validates :approval, presence: true

  def end_date_cannot_come_before_start_date
    if end_date.present? && end_date < start_date
      errors.add(:end_date, "must come after start date")
    end
  end
  #   def booking_dates_cannot_be_in_the_past
  #     if start_date.present? && start_date < Date.today
  #       errors.add(:start_date, "cannot be in the past")
  #     end
  #     if end_date.present? && end_date < Date.today
  #       errors.add(:end_date, "cannot be in the past")
  #     end
  #   end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :artworks, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :address, presence: true
  validates :email, uniqueness: true
  validates :email, presence: true
  # validates :email, format: { :with /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :address])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    if params[:query].present?
      @artworks = Artwork.global_search(params[:query])
    else
      @artworks = Artwork.all
    end
    @markers = @artworks.geocoded.map do |artwork|
      {
        lat: artwork.latitude,
        lng: artwork.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { artwork: artwork })
      }
    end
  end

  def show
    @artwork = Artwork.find(params[:id])
    @booking = Booking.new
  end

  def new
    @artwork = Artwork.new
  end

  def create
    @artwork = Artwork.new(artwork_params)
    @artwork.user = User.first # user should be the user logged into this session - needs to be added late
    if @artwork.save!
      redirect_to artwork_path(@artwork)
    else
      render :new
    end
  end

  def edit
    @artwork = Artwork.find(params[:id])
  end

  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy
    redirect_to my_artworks_path
  end

  private

  def artwork_params
    params.require(:artwork).permit(:name, :category, :description, :address, :rate, photos: [])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # def new
  #   @artwork = Artwork.find(params[:artwork_id])
  #   @booking = @artwork.bookings.new
  #   @booking.user = current_user
  # end

  def create
    @artwork = Artwork.find(params[:artwork_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.artwork = @artwork
    @booking.approval = false
    if @booking.save
      flash[:notice] = "Your artwork has been booked"
      redirect_to artwork_path(@artwork)
    else
      flash[:notice] = "Booking unsuccessful"
      render "artworks/show"
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to dashboard_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :approval)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @requests = Booking.where(user: current_user)
    @my_bookings = Booking.all.select{ |booking| booking.artwork.user == current_user }
  end
end

app/controllers/my_artworks_controller.rb
class MyArtworksController < ApplicationController
  def index
    @my_artworks = Artwork.where(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.where(artwork: params[:artwork])
  end

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
    @review.booking = @booking
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    if @review.save
      flash[:notice] = "Your review has been saved"
      redirect_to dashboard_path
    else
      flash[:notice] = "Review unsuccessful"
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/artworks/_booking-form.html.erb
<!-- Button trigger modal -->
<button type="button" class="button-outline" data-toggle="modal" data-target="#exampleModal">
  Book your BookArts
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title purple" id="exampleModalLabel">Booking</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="booking-form">
          <h3 class="purple">Book this artwork</h3>
          <%= simple_form_for [@artwork, @booking] do |f| %>
            <%= f.input :start_date %>
            <%= f.input :end_date %>
            <%= f.button :submit, class: 'button' %>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="button" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/artworks/_cards.html.erb
<div class="cards">
  <% @artworks.each do |artwork| %>
    <% background_url = cl_image_path artwork.photos.first.key %>
    <figure class="card card--1" style="--image-src: url('<%= background_url %>')">
      <figcaption>
        <span class="info-card">
          <h4><%= link_to artwork.name, artwork_path(artwork) %></h4>
          <p><strong>Owner: </strong><%= artwork.user.username %></p>
          <p><strong>Monthly rate: </strong>£ <%= artwork.rate %></p>
        </span>
      </figcaption>
    </figure>
  <% end %>
</div>

app/views/artworks/_carousel.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-6">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= cl_image_tag @artwork.photos.first.key, class: "carousel-photo"%>
          </div>
          <% @artwork.photos.to_a.slice(1, @artwork.photos.length).each do |photo| %>
            <div class="carousel-item">
              <%= cl_image_tag photo.key, class: "carousel-photo" %>
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/artworks/_form.html.erb
<%= simple_form_for(@artwork) do |f| %>
  <%= f.input :name, label: 'Name of the artwork' %>
  <%= f.input :category, collection: %w[painting drawing sculpture graphic\ design ceramic photography] %>
  <%= f.input :description , label: 'A brief description of the artwork' %>
  <%= f.input :rate, label: 'Rental price per month' %>
  <%= f.input :address, label: 'Address' %>
  <%= f.input :photos, as: :file, input_html: { multiple: true }, label: 'Add photos' %>
  <%= f.button :submit, class: 'button' %>
<% end %>

app/views/artworks/_info_window.html.erb
<div class="info-window d-flex m-1">
  <div class="mx-2">
    <p><%= artwork.name %></p>
    <p><%= artwork.user.username %></p>
    <p>£ <%= artwork.rate %></p>
  </div>
  <%= link_to artwork_path(artwork) do %>
    <%= cl_image_tag artwork.photos.first.key,height: 110, width: 80, crop: :fill, class: 'window-photo' %>
  <% end %>
</div>

app/views/artworks/_review.html.erb
<!-- Button trigger modal -->
<button type="button" class="button-outline" data-toggle="modal" data-target="#staticBackdrop">
  Reviews
</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title purple" id="staticBackdropLabel">Reviews</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class=" m-1">
            <% @artwork.reviews.each do |review| %>
              <div class="review-card">
                <div class="card-text">
                  <p><strong><%= "#{review.booking.user.username}" %></strong></p>
                <div>
                  <% counter = 0 %>
                  <% 5.times do %>
                    <i class="star-icon fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                    <% counter += 1 %>
                  <% end %>
                </div>
                <%= review.content %>
                </div>
              </div>
            <% end %>
         </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="button" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/artworks/index.html.erb
<div class="container">
  <div class="card-category navbar-margin" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.5)), url(https://i.pinimg.com/originals/4b/47/95/4b4795a58748405111bd7566b709eb52.jpg)">
    <h1>BookArts</h1>
      <div class="m-2">
        <%= form_tag artworks_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a artwork" %>
        <% end %>
      </div>
      <div class="mt-2">
        <p><strong>Share your talent with the world</strong></p>
      </div>
    </div>

  <div class="search-bar">
    <div id="map" class="my-4"
      style="height: 700px; width:400px"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <div class="right-side">
      <%= render "cards" %>
    </div>
  </div>
</div>

app/views/artworks/new.html.erb
<div class="container navbar-margin">
  <h1>Add a new artwork</h1>
  <%= render 'form', artwork: @artwork %>
  <div class="my-3">
    <%= link_to 'Back', artworks_path, class: 'button' %>
  </div>
</div>

app/views/artworks/show.html.erb
<div class="container justify-content-center navbar-margin">
  <div>
    <div class="art-info">
      <%= render 'carousel' %>
      <%# @artwork.photos.each do |photo| %>
        <%#= cl_image_tag photo.key, height: 500, width: 400, crop: :fill, class: "photo" %>
      <%# end %>
      <div class="art-info-description">
        <div class="name-card">
          <p>
          <span>
              <%= @artwork.name %>
            </span>
          &mdash; Owned by <%= @artwork.user.username %> &mdash;
          </p>
        </div>
        <p class="lightgray"> Rate £ <%= @artwork.rate %>/month</p>
        <p class="lightgray">Address: <%= @artwork.address %></p>
        <p class="description lightgray m-3"><%= @artwork.description %></p>
          <p class="m-2"><%= render "booking-form" %></p>
          <p class="m-2"><%= render "review" %></p>
      </div>
    </div>
  </div>
  <p class="m-3"><%= link_to 'Back', artworks_path, class: 'button' %></p>
</div>
</div>

app/views/dashboards/_approval.html.erb
<div>
  <div class="accept">
    <%= simple_form_for(booking) do |f| %>
      <%= f.input :approval, input_html: { value: true }, as: :hidden%>
      <%= f.button :button, "Accept", class: 'button' %>
    <% end %>
  </div>
  <div class="decline">
    <%= simple_form_for(booking) do |f| %>
      <%= f.input :approval, input_html: { value: false }, as: :hidden %>
      <%= f.button :button, "Decline", class: 'button' %>
    <% end %>
  </div>
</div>

app/views/dashboards/show.html.erb
<div class="container navbar-margin">
  <div class="dashboard-cards m-3">
    <div class="request-info" >
      <h2>Booking requests</h2>
      <% @requests.each do |request| %>
        <div class="booking-cards">
          <% artwork = request.artwork %>
          <% background_url = cl_image_path artwork.photos.first.key, height: 300, width: 500, crop: :fill %>
          <figure class="booking-card card--2" style="--image-src: url('<%= background_url %>')">
            <figcaption>
              <span class="info-card">
                <h4><%= link_to artwork.name, artwork_path(artwork) %></h4>
                <p><strong>Owner: </strong><%= request.artwork.user.username %></p>
                <p><strong>Monthly rate: </strong>£ <%= request.artwork.rate %></p>
                <p><strong>Booking Period: </strong><%= request.start_date %><span> - <%= request.end_date %></span></p>
                <p><strong>Status:</strong>
                  <% if request.approval == true%>
                    <span> Confirmed</span>
                  <% elsif request.approval.nil? %>
                    <span>Pending</span>
                  <% else %>
                    <span>Declined</span>
                  <% end %>
                </p>
                <%= link_to "Leave a review", new_booking_review_path(request), class: 'button' unless Date.today < request.end_date %>
                <% if Date.today < request.start_date %>
                  <%= link_to "Delete", request, method: :delete, data: {confirm: "Are you sure"}, class: "button" %>
                <% end %>
            </figcaption>
          </figure>
        </div>
      <% end %>
    </div>
    <div class="booking-info">
      <h2>Bookings</h2>
      <% @my_bookings.each do |booking| %>
        <div class="booking-cards">
          <% artwork = booking.artwork %>
          <% background_url = cl_image_path artwork.photos.first.key, height: 300, width: 500, crop: :fill %>
          <figure class="booking-card card--2" style="--image-src: url('<%= background_url %>')">
            <figcaption>
              <span class="info-card">
                <h4><%= link_to artwork.name, artwork_path(artwork) %></h4>
                <p><strong>Owner: </strong><%= artwork.user.username %></p>
                <p><strong>Monthly rate: </strong>£ <%= artwork.rate %></p>
                <p><strong>Booking Period: </strong><%= booking.start_date %><span> - <%= booking.end_date %></span></p>
                <p><strong>Status:</strong>
                  <% if booking.approval == true%>
                    <span> Confirmed</span>
                  <% elsif booking.approval.nil? %>
                    <span>Pending</span>
                  <% else %>
                    <span>Declined</span>
                  <% end %>
                </p>
                <%= render "approval", booking: booking %>
              </span>
            </figcaption>
          </figure>
        </div>
      <% end %>
    </div>
  </div>
  <%= link_to 'Back', artworks_path, class: 'button' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookArts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>

  </head>

  <body>
    <div class="wrapper">
      <%= render "shared/navbar" %>
      <%= yield %>
        <p class="notice"><%= notice %></p>
        <p class="sweet-alert"><%= alert %></p>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/my_artworks/index.html.erb
<div class="container navbar-margin">
  <div class="container-cards-my-artworks">
    <h1><%= "#{current_user.username}'s Artworks" %></h1>
    <div class="artwork-cards">
      <% @my_artworks.each do |artwork| %>
        <% background_url = cl_image_path artwork.photos.first.key, height: 300, width: 500, crop: :fill %>
        <figure class="myartwork-card card--1" style="--image-src: url('<%= background_url %>')">
          <figcaption>
            <div class="info-card">
              <h4><%= link_to artwork.name, artwork_path(artwork) %></h4>
              <p>
                <%= "£ #{artwork.rate}" %>
              </p>
              <%= link_to "Delete", artwork, method: :delete, data: {confirm: "Are you sure"}, class: 'button' %>
            </div>
          </figcaption>
        </figure>
      <% end %>
    </div>
    <p class="my-4"><%= link_to 'Add a new artwork', new_artwork_path, class: 'button', id: "sweet-alert-demo" %></p>
    <p><%= link_to "Back", artworks_path, class: 'button' %></p>
  </div>
</div>

app/views/pages/home.html.erb
<%-# Banner %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>BookArts - the nr 1 artworks marketplace </h1>
    <p>Don't let your creativity gather dust in a a corner: unleash it on the world!</p>
    <%= link_to "Start here", artworks_path, class: "btn btn-flat" %>
  </div>
</div>
<%-# Cards %>
<div class="container">
  <h2>How it works</h2>
  <div class="container-cards-how">
    <div class="card-how">
      <img src= "https://source.unsplash.com/random" width="200", height=150 alt= "Step 1">
      <h3>This is step 1</h3>
      <p>This is a description of step 1</p>
    </div>
    <div class="card-how">
      <img src= "https://source.unsplash.com/random" width=200 height=150 alt= "Step 2">
      <h3>This is step 2</h3>
      <p>This is a description of step 2</p>
    </div>
    <div class="card-how">
      <img src= "https://source.unsplash.com/random" width=200 height=150  alt= "Step 3">
      <h3>This is step 3</h3>
      <p>This is a description of step 3</p>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
  <%= simple_form_for([booking, review]) do |f| %>
    <%= f.input :content, label: 'Review' %>
    <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
    <%= f.button :submit, class: 'button' %>
  <% end %>

app/views/reviews/new.html.erb
<div class="container navbar-margin">
  <%= render 'form', review: @review, booking: @booking  %>
</div>

app/views/shared/_footer.html.erb
<div class="footer text-center mt-4">
  <div class="footer-links p-2">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon mb-3">
  <a class="navbar-brand" href="/">
    <p>BookArts</p>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to current_user.email, "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to current_user.username, "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://i.pinimg.com/564x/4f/e5/56/4fe556ff52197c197f42b636f58bb997.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Bookings", dashboard_path, class: "dropdown-item" %>
            <%= link_to "My Artworks", my_artworks_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>